language: node_js
node_js:
    - lts/*
cache:
  directories:
    - "node_modules"
script:
    - rm package-lock.json
    - npm install -g apmjs
    - apmjs install
    - npm run lint
    - make test-reports-ci
