language: node_js
node_js:
    - lts/*
env:
    - BROWSER=PhantomJS
cache:
  directories:
    - "node_modules"
script:
    - npm install -g apmjs
    - apmjs install
    - npm run lint
    - make test-reports-ci
