/*prerequisites*/
__inline("../lib/zepto.js");
__inline("../lib/zepto-callbacks.js");
__inline("../lib/zepto-deferred.js");
__inline("../lib/esl.js");

/*router*/
__inline('router/lang/extend.js');
__inline('router/lang/inherits.js');
__inline('router/emitter.js');
__inline('router/router/URL.js');
__inline('router/router/config.js');
__inline('router/router/controller.js');
__inline('router/router.js');
__inline('router/uri.js');
__inline('router/uri/URI.js');
__inline('router/uri/component/Abstract.js');
__inline('router/uri/component/Fragment.js');
__inline('router/uri/component/Host.js');
__inline('router/uri/component/Password.js');
__inline('router/uri/component/Path.js');
__inline('router/uri/component/Port.js');
__inline('router/uri/component/Query.js');
__inline('router/uri/component/Scheme.js');
__inline('router/uri/component/UserName.js');
__inline('router/uri/util/parse-query.js');
__inline('router/uri/util/stringify-query.js');
__inline('router/uri/util/uri-parser.js');

/*action*/
__inline('action.js');
__inline('service.js');
